function DNA_Sequence_Checker
% ============================================================
%          DNA SEQUENCE CHECKER - MATLAB GUI
%          Biotechnology Mini Project
% ============================================================

clc;

% ---------------- MAIN WINDOW ----------------
fig = uifigure( ...
    'Name','DNA Sequence Checker', ...
    'Position',[100 50 1250 750], ...
    'Color',[0.02 0.05 0.12]);

% ---------------- TITLE ----------------
uilabel(fig, ...
    'Text','🧬  DNA Sequence Checker', ...
    'Position',[300 680 600 45], ...
    'FontSize',28, ...
    'FontWeight','bold', ...
    'FontColor',[0.1 0.8 1]);

uilabel(fig, ...
    'Text','Analyze your DNA sequence and get detailed insights', ...
    'Position',[305 650 600 25], ...
    'FontSize',14, ...
    'FontColor',[0.7 0.8 0.95]);

% ============================================================
% LEFT PANEL - INPUT
% ============================================================

inputPanel = uipanel(fig, ...
    'Title',' Enter DNA Sequence ', ...
    'Position',[30 350 500 270], ...
    'BackgroundColor',[0.04 0.09 0.18], ...
    'ForegroundColor',[0.1 0.8 1], ...
    'FontSize',16);

uilabel(inputPanel, ...
    'Text','Enter DNA sequence (A, T, G, C only)', ...
    'Position',[25 200 400 25], ...
    'FontColor',[0.85 0.9 1], ...
    'FontSize',13);

sequenceBox = uitextarea(inputPanel, ...
    'Position',[25 95 450 100], ...
    'Value',{'ATGCGTACGTTAGC'}, ...
    'FontSize',15, ...
    'BackgroundColor',[0.02 0.05 0.12], ...
    'FontColor',[0.2 0.85 1]);

analyzeButton = uibutton(inputPanel, ...
    'push', ...
    'Text','▶  ANALYZE SEQUENCE', ...
    'Position',[25 35 280 45], ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'BackgroundColor',[0.05 0.55 0.95], ...
    'FontColor',[1 1 1], ...
    'ButtonPushedFcn',@analyzeDNA);

clearButton = uibutton(inputPanel, ...
    'push', ...
    'Text','↻  CLEAR', ...
    'Position',[320 35 155 45], ...
    'FontSize',13, ...
    'BackgroundColor',[0.08 0.12 0.22], ...
    'FontColor',[0.8 0.9 1], ...
    'ButtonPushedFcn',@clearAll);

% ============================================================
% ANALYSIS STATUS
% ============================================================

statusPanel = uipanel(fig, ...
    'Title',' Analysis Status ', ...
    'Position',[560 540 650 80], ...
    'BackgroundColor',[0.02 0.25 0.25], ...
    'ForegroundColor',[0.2 1 0.8], ...
    'FontSize',14);

statusLabel = uilabel(statusPanel, ...
    'Text','✓  Ready for DNA sequence analysis', ...
    'Position',[25 15 580 30], ...
    'FontSize',16, ...
    'FontWeight','bold', ...
    'FontColor',[0.2 1 0.8]);

% ============================================================
% SEQUENCE OVERVIEW
% ============================================================

overviewPanel = uipanel(fig, ...
    'Title',' Sequence Overview ', ...
    'Position',[560 320 650 200], ...
    'BackgroundColor',[0.04 0.09 0.18], ...
    'ForegroundColor',[0.1 0.8 1], ...
    'FontSize',15);

uilabel(overviewPanel, ...
    'Text','DNA Sequence:', ...
    'Position',[25 140 130 25], ...
    'FontColor',[0.3 0.7 1], ...
    'FontSize',13);

sequenceResult = uilabel(overviewPanel, ...
    'Text','-', ...
    'Position',[160 140 450 25], ...
    'FontColor',[1 1 1], ...
    'FontSize',13);

uilabel(overviewPanel, ...
    'Text','Sequence Length:', ...
    'Position',[25 105 130 25], ...
    'FontColor',[0.3 0.7 1], ...
    'FontSize',13);

lengthResult = uilabel(overviewPanel, ...
    'Text','-', ...
    'Position',[160 105 100 25], ...
    'FontColor',[1 1 1], ...
    'FontSize',13);

% Nucleotide labels
AResult = createResultLabel(overviewPanel,'A',25,45,[0.1 0.8 0.4]);
TResult = createResultLabel(overviewPanel,'T',150,45,[1 0.3 0.4]);
GResult = createResultLabel(overviewPanel,'G',275,45,[1 0.6 0.1]);
CResult = createResultLabel(overviewPanel,'C',400,45,[0.2 0.5 1]);

% ============================================================
% GC / AT CONTENT
% ============================================================

contentPanel = uipanel(fig, ...
    'Title',' GC / AT Content ', ...
    'Position',[560 110 650 190], ...
    'BackgroundColor',[0.04 0.09 0.18], ...
    'ForegroundColor',[0.1 0.8 1], ...
    'FontSize',15);

uilabel(contentPanel, ...
    'Text','GC Content', ...
    'Position',[30 120 150 25], ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'FontColor',[0.2 0.85 1]);

GCLabel = uilabel(contentPanel, ...
    'Text','0.00%', ...
    'Position',[180 120 100 25], ...
    'FontSize',14, ...
    'FontColor',[1 1 1]);

GCBar = uigauge(contentPanel, ...
    'Position',[20 30 260 80], ...
    'Limits',[0 100], ...
    'Value',0);

uilabel(contentPanel, ...
    'Text','AT Content', ...
    'Position',[350 120 150 25], ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'FontColor',[0.75 0.3 1]);

ATLabel = uilabel(contentPanel, ...
    'Text','0.00%', ...
    'Position',[500 120 100 25], ...
    'FontSize',14, ...
    'FontColor',[1 1 1]);

ATBar = uigauge(contentPanel, ...
    'Position',[340 30 260 80], ...
    'Limits',[0 100], ...
    'Value',0);

% ============================================================
% COMPLEMENTARY DNA
% ============================================================

compPanel = uipanel(fig, ...
    'Title',' Complementary Sequences ', ...
    'Position',[30 100 500 220], ...
    'BackgroundColor',[0.04 0.09 0.18], ...
    'ForegroundColor',[0.1 0.8 1], ...
    'FontSize',15);

uilabel(compPanel, ...
    'Text','Complementary DNA', ...
    'Position',[25 150 200 25], ...
    'FontColor',[0.2 0.85 1], ...
    'FontSize',13);

compResult = uilabel(compPanel, ...
    'Text','-', ...
    'Position',[25 110 450 30], ...
    'FontColor',[1 1 1], ...
    'FontSize',13);

uilabel(compPanel, ...
    'Text','Reverse Complement', ...
    'Position',[25 70 200 25], ...
    'FontColor',[0.7 0.4 1], ...
    'FontSize',13);

reverseResult = uilabel(compPanel, ...
    'Text','-', ...
    'Position',[25 30 450 30], ...
    'FontColor',[1 1 1], ...
    'FontSize',13);

% ============================================================
% GRAPH
% ============================================================

graphPanel = uipanel(fig, ...
    'Title',' Nucleotide Distribution ', ...
    'Position',[30 10 500 80], ...
    'BackgroundColor',[0.04 0.09 0.18], ...
    'ForegroundColor',[0.1 0.8 1], ...
    'FontSize',13);

% ============================================================
% CALLBACK - ANALYZE DNA
% ============================================================

    function analyzeDNA(~,~)

        DNA = upper(strjoin(sequenceBox.Value,''));
        DNA = strrep(DNA,' ','');

        % Validate
        if isempty(DNA)
            uialert(fig,'Please enter a DNA sequence.','Input Error');
            return;
        end

        if any(~ismember(DNA,'ATGC'))
            uialert(fig, ...
                'Invalid DNA sequence! Only A, T, G and C are allowed.', ...
                'Invalid Sequence');
            return;
        end

        % Counts
        A = sum(DNA == 'A');
        T = sum(DNA == 'T');
        G = sum(DNA == 'G');
        C = sum(DNA == 'C');

        L = length(DNA);

        GC = ((G+C)/L)*100;
        AT = ((A+T)/L)*100;

        % Complement
        Complement = DNA;

        Complement(DNA=='A') = 'T';
        Complement(DNA=='T') = 'A';
        Complement(DNA=='G') = 'C';
        Complement(DNA=='C') = 'G';

        ReverseComplement = fliplr(Complement);

        % Update UI
        statusLabel.Text = '✓  Analysis Complete!';
        statusLabel.FontColor = [0.2 1 0.8];

        sequenceResult.Text = DNA;
        lengthResult.Text = num2str(L);

        AResult.Text = sprintf('A   %d',A);
        TResult.Text = sprintf('T   %d',T);
        GResult.Text = sprintf('G   %d',G);
        CResult.Text = sprintf('C   %d',C);

        GCLabel.Text = sprintf('%.2f%%',GC);
        ATLabel.Text = sprintf('%.2f%%',AT);

        GCBar.Value = GC;
        ATBar.Value = AT;

        compResult.Text = Complement;
        reverseResult.Text = ReverseComplement;

        % Graph window
        graphFig = uifigure( ...
            'Name','Nucleotide Distribution', ...
            'Position',[300 150 600 450], ...
            'Color',[0.02 0.05 0.12]);

        ax = uiaxes(graphFig, ...
            'Position',[60 70 500 320]);

        bar(ax,[A T G C]);

        ax.XTick = 1:4;
        ax.XTickLabel = {'A','T','G','C'};
        ax.FontSize = 13;
        ax.XColor = [0.8 0.9 1];
        ax.YColor = [0.8 0.9 1];
        ax.Color = [0.02 0.05 0.12];

        title(ax,'DNA Nucleotide Distribution', ...
            'Color',[0.1 0.8 1], ...
            'FontSize',16);

        xlabel(ax,'Nucleotide');
        ylabel(ax,'Count');

        grid(ax,'on');

    end

% ============================================================
% CLEAR BUTTON
% ============================================================

    function clearAll(~,~)

        sequenceBox.Value = {''};

        sequenceResult.Text = '-';
        lengthResult.Text = '-';

        AResult.Text = 'A   0';
        TResult.Text = 'T   0';
        GResult.Text = 'G   0';
        CResult.Text = 'C   0';

        GCLabel.Text = '0.00%';
        ATLabel.Text = '0.00%';

        GCBar.Value = 0;
        ATBar.Value = 0;

        compResult.Text = '-';
        reverseResult.Text = '-';

        statusLabel.Text = '✓  Ready for DNA sequence analysis';

    end

end

% ============================================================
% FUNCTION FOR RESULT LABELS
% ============================================================

function label = createResultLabel(parent,text,x,y,fontColor)

label = uilabel(parent, ...
    'Text',[text '   0'], ...
    'Position',[x y 100 30], ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'FontColor',fontColor);

end